### ISSUE TITLE
BUG: when mongod is restarted, application goes in unrecoverable state.

### ISSUE THREAD

**Issue by jigargosar** [jdesboeufs/connect-mongo#23]
- And contineously gives error "Error: no open connections"
- why is connection establishment not retried?

**Comment by pareshgehlot** [comment]
I have the same issue...

My node app suddenly is not able to connect to mongo db

It continuously gives "no open connections" error

Even though my mongo db service is active.

Am not facing this with mongoose, but am facing it with "connect-mongo"

Once this issue rises its ugly head, if I restart my node app, connect-mongo is again able to connect to mongo db again.

1. I don't know the exact reason, why it is happening? want to know the root cause

2. I don't know why after restarting node app, connect-mongo is able to connect again to db.

3. I tried "auto_reconnect" : "true", but in this case what happens is, my website continuously keeps on loading, as though the mongodb service is active, somehow connect-mongo looses db connection, and is unable to connect.

This is really causing a bad impact on my site.

I request everyone to help.

Every help will be greatly appreciable.

Thanks in advance
