### ISSUE TITLE
The event of "destory" not be triggered after the session has been  destroyed

### ISSUE THREAD

**Issue by hlerenow** [jdesboeufs/connect-mongo#247]
The event of "destroy" not be triggered after the session has been  destroyed,I use the  mongodDB

**Comment by jdesboeufs** [comment]
The `destroy` event is emitted when your session manager (`express-session`) call `destroy()` but not when the session expires.

**Comment by mymainmanbrown** [comment]
Is there a "recommended" way to get the session before it is destroyed?  For instance, I would like to do certain things with the id of the user that is part of my passport session, but all I have access to is the id of the session, which is at this point useless since I can't look that session up.  In looking through the source, the event is definitely emitted after the session is removed (after `collection.removeAsync`).  What about a pre-destroy event that passes the cached session?

**Comment by devalexqt** [comment]
Event "destroy" not emited for me too.
