### ISSUE TITLE
Next major release

### ISSUE THREAD

**Issue by jdesboeufs** [jdesboeufs/connect-mongo#284]
I'm planning to work on the next major release in the following weeks.
This next version will focus on `mongoose@5` and `mongodb@3`.
I consider dropping support of previous versions, since they are supported by `connect-mongo@2`.
Node.js 4 may also be dropped.

Feed free to discuss this position ;)

**Comment by thor84no** [comment]
Are you aware that the mongodb connector you're using is specifically not compatible with mongodb 3.6? I'm just asking because the README says "Support MongoDB >= 3.0", but you're depending on "^2.0.36" which at the moment evaluates to 2.2.35.

According to [mongodb docs](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-node) 2.2 does not support mongodb 3.6. We're having some issues in our mongodb upgrade process that we think we've tracked down to this package.

Do you expect that this major release will fix this? Is there anything we can do to help make that upgrade happen?

**Comment by jdesboeufs** [comment]
There is no compatibility issue with MongoDB 3.6 since `connect-mongo`
doesn’t use new MongoDB features.

The `mongodb` dependency is used when a connection string is provided. You
can also pass your own database instance ou promise.

**Comment by thor84no** [comment]
You don't necessarily have to be using new mongo features for it to be incompatible; there are significant changes to the underlying protocol for 3.6. We had to upgrade despite not using any new features ourselves. We do however pass the database handle in, so perhaps that's not the problem, but there are API diferences between 2.2 and 3.0 connectors so it could still be causing issues. Unfortunately the errors are very intermittent so it's hard to get it nailed down for sure what the problem is, but our sessions are definitely disappearing.

**Comment by jdesboeufs** [comment]
At French government we currently use MongoDB 3.6 with connect-mongo@2 and
mongodb@2.2.

No problem to update. But currently connect-mongo doesn’t work properly
with mongodb@3.

You can help in provinding investigation or tests.
I’m currently rewritting old tests with ava.

**Comment by thor84no** [comment]
So does that mean that our problem could be caused by passing a 3.0.2 mongodb connector to connect-mongo? I'll certainly have a go at investigating it; if I come up with anything I'll be sure to message you/provide a PR. Thanks.

**Comment by carlsonp** [comment]
Here are the [migration notes for Mongoose v5](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md).

**Comment by CruiseMan** [comment]
@jdesboeufs Do you have ETA fro major upgrade ?.

**Comment by jdesboeufs** [comment]
No :(
I'm very busy, so I'm also looking for additional maintainers.

**Comment by YasharF** [comment]
Thank you for the great work.  I am happy to see that @mingchuno was also able to help with the maintenance.  Do you need help to get the next version released to npm's repo?
