### ISSUE TITLE
MongoError: E11000 duplicate key error collection:

### ISSUE THREAD

**Issue by eladvider-softangible** [jdesboeufs/connect-mongo#287]
Hi,
i'm getting this error message somtimes.

I have a relatively large site that uses  mongoDB with replications.

i tried to clear the session document and this appear again.

Thanks

**Comment by vandernorth** [comment]
Hi,

Facing the same issue. It doesn't seem to be connect-mongo code change issue because I was still using v1.2 and this issue happend anyway. Might be one of the dependencies. 

I saw the same issue in other mongodb session store: https://github.com/adrai/sessionstore/issues/43 and a StackOverflow question here: https://stackoverflow.com/questions/49963718/connect-mongo-causing-mongoerror-e11000-duplicate-key-error-collection/50012786#50012786

My StackTrace:
`MongoError: E11000 duplicate key error collection: sessions index: _id_ dup key: { : "ecFQXkfYbZJ185f6gYm0ILjxds0T7UvV" }
    at Function.MongoError.create (/usr/lib/node_modules/***/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/usr/lib/node_modules/***/node_modules/mongoose/node_modules/mongodb/lib/utils.js:139:22)
    at /usr/lib/node_modules/***/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1060:67
    at /usr/lib/node_modules/***/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

MongoDB-Core is version 2.1.15
Mongoose is version 4.11.14

Will try to update to 2.* and post the results.

**Comment by eladvider-softangible** [comment]
Hi,
To slove the problem i change the id that genertated from 'express session' by the following code:

```
var uuidv4 = require('uuid/v4');
app.use(session({
  genid: function(req) {
  	return uuidv4() 
  }

}))
```

**Comment by azcn2503** [comment]
The `genid` solution does not work for me. It continues to create duplicate keys, just under a uuid format instead of the default format.

**Comment by SyedSaifAli** [comment]
Any solution to the above problem?

**Comment by mingchuno** [comment]
@azcn2503 @eladvider-softangible @SyedSaifAli Do you guys have a clear step to reproduce the issues? From the surface, it may look like the default `genid ` method in `expressjs/session` produce duplicated key when you have large amount of records? Did you guys enable the session expiration feature to clean up unused session?
