### ISSUE TITLE
Share session between two node apps

### ISSUE THREAD

**Issue by kevinprotoss** [jdesboeufs/connect-mongo#98]
Hello,

Does any one knows whether can a session be shared between two separate node apps by using connect-mongo? These two apps listen on different ports and I set the reverse proxy in the nginx. They have domains as the following:
www.mydomain.com
forum.mydomain.com
The second one is the subdomain. Is it possible to share session between them?

Best regards,
Kevin

**Comment by johnwp** [comment]
This sort of thing might actually be useful to me. I'm trying to figure out the best approach to share immutable session data one-way.

In my Express/Angular app, I'm currently passing the session ID in the header of all requests to a separate Express/Mongoose REST API application. The Express/Mongoose application has direct access to the sessions collection. I'm currently looking up that session, grabbing user information from it, and making sure it's valid for all of my API endpoints.

It might be more efficient to just grab that data from the session instead of hitting the DB every time, but maybe my whole approach is wrong.
